version: '3.8'

services:
  card-game:
    container_name: card-game
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 9000:9000
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - card-game-mysql
    networks:
      - card-game-network
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    env_file:
      - .env

  card-game-mysql:
    container_name: card-game-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - card-game-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - card-game-network
    env_file:
      - .env
volumes:
  card-game-data:
networks:
  card-game-network: